[package]
name = "vienna-runner"
version = "0.1.0"
authors = ["Jean Mertz <git@jeanmertz.com>"]
edition = "2018"
publish = false

[dependencies]
engine = { package = "vienna-engine", path = "../engine" }
